### ISSUE TITLE
My Json doesn't work

### ISSUE THREAD

**Issue by JoaoNunoBrito** [icepeng/sw-penguin#2]
![screenshot_1](https://user-images.githubusercontent.com/11439750/48680428-64e13200-eb93-11e8-9533-791734d6321b.png)

**Comment by icepeng** [comment]
Did you exported your data with SW Exporter?

It may not work correctly for JSON extracted by other program.

**Comment by JoaoNunoBrito** [comment]
Yes, it's account related. I exported for 2 accounts, my other one worked fine. I assume it's a json parsing error perhaps (I have not edited the json)

**Comment by icepeng** [comment]
Can you create a gist and copy&paste json?

**Comment by JoaoNunoBrito** [comment]
[cdea75ccdbfa0c4b043df70dcf6be06b-75a9760ffe41a01ff33f1fd92111c005a10bf2c6.zip](https://github.com/icepeng/sw-penguin/files/2594448/cdea75ccdbfa0c4b043df70dcf6be06b-75a9760ffe41a01ff33f1fd92111c005a10bf2c6.zip)

**Comment by icepeng** [comment]
I assumed that "runes" should be array type, but some of the "runes" are array-like object type. Such as

```
{
"0": ...
"1": ...
}
```

I never saw this behavior before, might be a bug from SW Exporter. I will handle this case, but I think you have to report this file to https://github.com/Xzandro/sw-exporter

**Comment by JoaoNunoBrito** [comment]
Thank you for your time :) 
Will do!

**Comment by icepeng** [comment]
Tested & Published.
If the error still occurs, remove browser cache and try it again.
